config/routes.rb
Eventsroundme::Application.routes.draw do
  get "normal_user/dashboard" =>"normal_user#dashboard"
  match "normal_user/add_event_normal_user" =>"normal_user#add_event_normal_user"
  match "normal_user/events_attending" =>"normal_user#events_attending"
  match "normal_user/find_friends" =>"normal_user#find_friends"
  match "normal_user/category_order" =>"normal_user#category_order"
  match "normal_user/create_event" =>"normal_user#create_event"
  match "normal_user/thank_you_after_payment" =>"normal_user#thank_you_after_payment"
  match "normal_user/paypal_notification" =>"normal_user#paypal_notification"
  match "normal_user/edit_event_by_normal_user/:id" =>"normal_user#edit_event_by_normal_user"
  match "normal_user/delete_user_event/:id" =>"normal_user#delete_user_event"
 
  root :to => "events#index"
  
  match "/contact"  => "contacts#new", as: :contact_us
  match "/test"   => "static#test"
  match '/auth/:provider/callback' => 'authentications#create'

  resources :contacts

  devise_for :admin_users, ActiveAdmin::Devise.config


  resources :searches

  get "events-in/(:name)/(:id)" => "searches#events_search", as: :events_search

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
 
  get "events/city/:name" => "searches#events_by_city"

  get "popup/events_around_me"
  get "popup/homepage"
  get "popup/signup"

  get "/fetch_event" => "events#fetch_event", :via => ["options", "get", "post"]
  get "/fetch_all_city" => "events#fetch_all_city", :via => ["options", "get", "post"]

  # get "/:action"    => "static#:action"

  resources :categories
  resources :events 
  ActiveAdmin.routes(self)  
end

app/controllers/events_controller.rb
require 'open-uri'

class EventsController < ApplicationController
  before_filter :set_data_variable
  
  def set_data_variable
    @data = Hash.new
  end

  # GET /events/city/City-name
  def events_by_city
    @events = Event.where(:city => params[:city].to_s)
    
    respond_to do |format|
      format.html # events_by_city.html.haml
      format.json { render json: @events }
    end    
  end

  def fetch_event
    @event = Event.where("LOWER(city) LIKE ? and starting_at > ?","%#{params[:city].to_s.downcase}%",Time.now)
    events= @event.to_json
    respond_to do |format|
       format.json{render :json => events, :callback => params[:callback]}
    end
  end

  def fetch_all_city
    @event = Event.select(:city).uniq
    events= @event.to_json
    respond_to do |format|
       format.json{render :json => events, :callback => params[:callback]}
    end
  end

  # GET /events
  # GET /events.json
  def index
    # Event.where("starting_at < '#{Time.now.to_date}'").destroy_all
    
    data = serach_local_events(request);
    unless data.nil?
      @events_array = []
      @data[:events].each do |event|
      

        @match_city = 0
        
        final_address_string = (event.address + event.city + event.country + event.state).split(/\s+(?=(?:[^"]*"[^"]*")*[^"]*$)/);
        search_string = @city.gsub(/\s+/, ' ').split(" ");

        search_string.each do |f|
          final_address_string.each do |ff|
            unless ff.downcase.match(f.downcase).nil?
              @match_city = @match_city+1
            end
          end          
        end

        unless event.starting_at.blank?
          if event.starting_at.to_date >= Time.now.to_date and @match_city == search_string.count
            @events_array << event
          end
        else
          if @match_city == search_string.count
            @events_array << event
          end
        end  
        
      end
      @data[:events] = @events_array
      @data[:events] = @data[:events].sort { |x,y| y.starting_at.to_date <=> x.starting_at.to_date }
      @data[:events] = @data[:events].reverse
    end  


    unless data.nil?
      if params[:page].nil?
        @data[:events] = @data[:events].first(9);
      else
        limit = params[:page].to_i*9
        @data[:events] = @data[:events].drop(limit-9).first(9);
      end      
    end
    @data[:events] = Event.last(9) unless data
    @search = Search.new
    
    respond_to do |format|
      format.html # index.html.haml
      # format.json { render json: @events }
      format.json { render :json => {:html => render_to_string(:partial => "event.html.haml")}.to_json }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    if @event.blank?
      redirect_to :back and return
    else
      @event.update_event_data
    end
    
    location = @event.city unless @event.city.blank?
    location = @event.country if @event.city.blank?    

    @cal_url = generate_calendar_button(@event.event_name, @event.event_name, @event.starting_at, @event.ending_at, location,"http://nir-event.herokuapp.com", "Nir Event")
    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def search
    if request.post?
      search = Search.new(
        :search_string => params[:search],
        :ip_address    => request.remote_ip
      )
      # search_results = Event.
    end

    respond_to do |format|
      format.html
      format.json
    end
  end
end

private

def generate_calendar_button(name, description, start, end_time, location, mysite_url, mysite_name) 
   google_url = 'http://www.google.com/calendar/event?action=TEMPLATE'
   google_url += URI.encode("&text=#{name}")
   if !start.blank? and !end_time.blank?
      google_url += URI.encode("&dates=#{start.strftime('%Y%m%dT%H%M')}00/#{end_time.strftime('%Y%m%dT%H%M')}00")      
   end    
   google_url += URI.encode("&details= For details visit: #{mysite_url}")
   google_url += URI.encode("&location=#{location}")
   google_url += URI.encode("&sprop=#{mysite_url}")
   google_url += URI.encode("&sprop=name:#{mysite_name}")
   return google_url
end

def serach_local_events(request)
  # return nil if request.location.nil?
  # @city = request.location.data["city"].blank? ? request.location.data["country_name"] : request.location.data["city"] 
  # return nil if @city.blank?
  # @city.downcase.gsub("-"," ").gsub(","," ").gsub(/\s+/, ' ');
  
  @city = locateAddressByIp(request.location.data["ip"])
  @search_string = {
      start_date: '',
      end_date: '',
      city: @city,
      text: '',
      site: 'All'
    }
    

    @search = Search.where(search_string: @search_string.to_yaml)
     if @search.blank? 
      @search = Search.new(
        :search_string => @search_string,
        :ip_address => "" # params[:search][:ip_address]
      )
      @search.save
     else
        @search = @search.first
     end

    # if true # or @search.event_list.blank?
    event_list = Event.new.combined_search_results(@search.search_string)
    @search.update_attribute :event_list, event_list
    # end

    event_list = event_list.blank? ? @search.event_list : event_list

    if event_list.blank?
      @data[:events] = []
    elsif event_list.count == 1
      @data[:events] = Event.where("id in (#{event_list.join})")
    elsif event_list.count > 1
      @data[:events] = Event.where("id in (#{event_list.join(',')}) AND starting_at > '#{Time.now.to_date}' AND (ending_at > '#{Time.now.to_date}' OR ending_at IS NULL)")
    end
end

def locateAddressByIp(ip)
  doc = Nokogiri::HTML(open("http://api.ipinfodb.com/v3/ip-city/?key=#{ENV['IP_INFO_DB_API_KEY']}&ip=#{ip}"))
  city = doc.text.split(';')[6].try(:strip).try(:downcase)
  city
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<% @data[:events].each do |event| %>
  <div class="event">
      <div class="event_head">
        <% if event.from_meetup? %>
              <a href="<%= event.image_link%>"><img src="/assets/meet.png"/></a>
          <% elsif event.from_facebook? %>
              <a href="<%= event.image_link%>"><img src="/assets/f.png"/></a>
          <% elsif event.from_eventbrite?%>
              <a href="<%= event.image_link%>"><img src="/assets/e.png"/></a>
          <% end %>                              
          <p><img src="/assets/location_icon.png"/>
            <% if event.city.blank? and event.country.blank? %>
              <%= event.address %>
            <% else %>
              <%= event.city %>, <%= event.country%>
            <% end %>                                
          </p>
          <p><img src="/assets/calender_icon.png"/><%= event.date%></p>
      </div>
      <div class="event_body">
          <a href="<%=event_path(event)%>"><h3><%= event.event_name%></h3></a>
          <p><%=strip_tags(event.event_short_description)%></p>
      </div>
  </div>
<% end %>

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :source
    = f.text_field :source
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.erb
    <div class="banner_con">
        <h2>If it's out there you'll find it here</h2>
        <p>A New way to discover everything interesting around you</p>        
    </div>

    <div class="container">

        <div class="row-fluid">
            <div class="span3">
                <%= form_for @search do |f|%>
                <div class="sort_event">                  
                    <h2>Sort events</h2>
                    <h4>Going</h4>
                     <input type="text" id="start_date" placeholder="From" name="start_date" autocomplete="off">
                     <input type="text" id="end_date" placeholder="To" name="end_date" autocomplete="off"> 
                    <h4>Where are you looking?</h4>
                    <input type="text" id="searchTextField" required="true" placeholder="Enter city name.." name="location" autocomplete="off">   
                    <div id="map-canvas"></div>
                    <select>
                        <option>up to 10 km</option>
                        <option>up to 20 km</option>
                        <option>up to 30 km</option>
                        <option>up to 40 km</option>
                    </select>

                    <h4>Source</h4>
                    <!-- <label><input type="checkbox">Eventbrite</label>
                    <label><input type="checkbox">Meetup</label>
                    <label><input type="checkbox">Facebook</label> -->
                     <%= select "select", "site", ["All","Facebook","Meetup","Eventbrite"], {:selected => "All"}, {:id => 'select_site', :name => "select_site"} %>
                     <%= f.hidden_field :ip_address, value: request.remote_ip %>

                    <h4>Interest</h4>
                    <!-- <label><input type="checkbox">Tech</label>
                    <label><input type="checkbox">Sport</label>
                    <label><input type="checkbox">Music</label>
                    <label><input type="checkbox">Show</label>
                    <label><input type="checkbox">Lacture</label>
                    <label><input type="checkbox">Gathering</label> -->
                    <input type="text" id="search_query" placeholder="lecture, meetups.." name="search_string" autocomplete="off">
                    <%= f.button 'Search', class: 'btn', type: 'button', id: 'search_button'%>
                </div>
                <% end %>
            </div>
            <div class="span6">
                <div class="" id="eventUl">
                    <% @data[:events].each do |event| %>
                      <div class="event">
                          <div class="event_head">
                            <% if event.from_meetup? %>
                                  <a href="<%= event.image_link%>"><img src="/assets/meet.png"/></a>
                              <% elsif event.from_facebook? %>
                                  <a href="<%= event.image_link%>"><img src="/assets/f.png"/></a>
                              <% elsif event.from_eventbrite?%>
                                  <a href="<%= event.image_link%>"><img src="/assets/e.png"/></a>
                              <% end %>                              
                              <p><img src="/assets/location_icon.png"/>
                                <% if event.city.blank? and event.country.blank? %>
                                  <%= event.address %>
                                <% else %>
                                  <%= event.city %>, <%= event.country%>
                                <% end %>                                
                              </p>
                              <p><img src="/assets/calender_icon.png"/><%= event.date%></p>
                          </div>
                          <div class="event_body">
                              <a href="<%=event_path(event)%>"><h3><%= event.event_name%></h3></a>
                              <p><%=strip_tags(event.event_short_description)%></p>
                          </div>
                      </div>
                    <% end %>
                </div>
            </div>
            <div class="span3 suggested_evnt">
                <h2>Suggested events</h2>
                <div>
                    <h3>Wix TLV Hackathon</h3>
                    <a href="#"><img src="/assets/event-round.jpg"/></a>
                    <p><img src="/assets/location_icon.png"/>wix HQ, HaNamal 40</p>
                    <p><img src="/assets/calender_icon.png"/>october 3th, 2012  6:30pm</p>
                </div>
            </div>
        </div>
    </div>

<div style="display:none;" id="wait_dialog" class="modal fade in" aria-hidden="false">
  <div class="modal-header">
    <h5 style="text-align:center !important">
      We do our best to find you event, please wait.
      <br>
    </h5>
  </div>
  <div class="modal-body">
  <table>
    <tbody>
      <tr valign="top">
        <td style="text-align:center !important">
          <p>
            <img src="/assets/progress.gif" alt="Progress">
          </p>
        </td>
      </tr>
    </tbody>
  </table>
</div>
</div>     

<p><%= @city%></p>

<script type="text/javascript">
    var $ = $.noConflict(true);
    $("#start_date, #end_date").datepicker({
    "dateFormat":"dd-mm-yy"
    })
</script>  

<script type="text/javascript">
  $("#search_button").click(function(){
     $("#new_search").submit();
     $('html, body').animate({scrollTop:0}, '1000', 'swing', function() { 
         $("#wait_dialog").show();
         $('.banner_con').css({'opacity':'.5'});
         $('.container').css({'opacity':'.5'});     
      });
  });
</script> 

<script type="text/javascript">
  var page = 2;
  $(window).scroll(function () {
       if ($(window).scrollTop() == $(document).height() - $(window).height()) {
           getEvents();
           page = page+1;
       }
   });
</script>

<script type="text/javascript">
  function getEvents() {
       $.ajax(
        {
            type: "GET",
            url: "/",
            data: "page="+page,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            cache: "false",

            success: function (data) {
              $('#eventUl').append(data.html);
            },

            Error: function (x, e) {
                alert("Some error");
            }
        });
   }
</script>

<style type="text/css">
  .ui-datepicker-calendar {width:99% !important;}
  .pac-container:after{background-image:none !important;} 
</style>  

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
<script type="text/javascript">
  function initialize() {
    var mapOptions = {
      center: new google.maps.LatLng(-33.8688, 151.2195),
      zoom: 13,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);
  
    var input = (document.getElementById('searchTextField'));
    var autocomplete = new google.maps.places.Autocomplete(input);
  
    autocomplete.bindTo('bounds', map);
  
    var infowindow = new google.maps.InfoWindow();
    var marker = new google.maps.Marker({
      map: map
    });
  
    google.maps.event.addListener(autocomplete, 'place_changed', function() {
      infowindow.close();
      marker.setVisible(false);
      input.className = '';
      var place = autocomplete.getPlace();
      if (!place.geometry) {
        // Inform the user that the place was not found and return.
        input.className = 'notfound';
        return;
      }
  
      // If the place has a geometry, then present it on a map.
      if (place.geometry.viewport) {
        map.fitBounds(place.geometry.viewport);
      } else {
        map.setCenter(place.geometry.location);
        map.setZoom(17);  // Why 17? Because it looks good.
      }
      marker.setIcon(({
        url: place.icon,
        size: new google.maps.Size(71, 71),
        origin: new google.maps.Point(0, 0),
        anchor: new google.maps.Point(17, 34),
        scaledSize: new google.maps.Size(35, 35)
      }));
      marker.setPosition(place.geometry.location);
      marker.setVisible(true);
  
      var address = '';
      if (place.address_components) {
        address = [
          (place.address_components[0] && place.address_components[0].short_name || ''),
          (place.address_components[1] && place.address_components[1].short_name || ''),
          (place.address_components[2] && place.address_components[2].short_name || '')
        ].join(' ');
      }
  
      infowindow.setContent('' + place.name + '' + address);
      infowindow.open(map, marker);
    });
  
    // Sets a listener on a radio button to change the filter type on Places
    // Autocomplete.
    function setupClickListener(id, types) {
      var radioButton = document.getElementById(id);
      google.maps.event.addDomListener(radioButton, 'click', function() {
        autocomplete.setTypes(types);
      });
    }
  
    setupClickListener('changetype-all', []);
    setupClickListener('changetype-establishment', ['establishment']);
    setupClickListener('changetype-geocode', ['geocode']);
  }
  
  google.maps.event.addDomListener(window, 'load', initialize); 

</script>



<!-- .hero.hidden-phone
  .container
    .row
      .span12
        = image_tag "hero.png", :alt=>"1-1"
        .calltoaction
          %h2.heading If it's out there we'll find it
          .description
            The way to discover and book interesting real events
.container
  .row-fluid
    = form_for @search, html: {class: 'form-inline search_bar', style: 'text-align:center'} do |f|
      Going
      %input.input-small#start_date{:placeholder => "From", :type => "text", name: "start_date"}
      %input.input-small#end_date{:placeholder => "To", :type => "text", name: "end_date"}
      In:
      %input#searchTextField{:placeholder => "Enter city name...","autocomplete"=>"off", :type => "text", name: "location", required: true}
      Interested in:
      %input#search_query{:placeholder => "lecture, meetups...", :type => "text", name: "search_string"}
      = f.hidden_field :ip_address, value: request.remote_ip
      = select "select", "site", ["All","Facebook","Meetup","Eventbrite"], {:selected => "All"}, {:id => 'select_site', :name => "select_site"}
      = f.button 'Search', class: 'btn', type: 'button', id: 'search_button'
      %span.pull-right
        / %button.btn.btn-success{:type => "button"}
        /   %i.icon-map-marker
        /   Search by your place now
  .row-fluid.results
    .container-fluid
      %ul.thumbnails.span12.offset1#eventUl
        - @data[:events].each do |event|
          %li.span3.pull-left{style: "box-shadow: 0 0 10px blanchedalmond, 0 0 2px blueviolet;height: 400px;margin-left: 0;margin-right: 50px;padding: 10px;"}
            %a.thumbnail{:href => event_path(event)}
              .tag
                - if event.from_meetup?
                  = image_tag "meetuptag.png"
                - if event.from_facebook?
                  = image_tag "facebooktag.png"
                - if event.from_eventbrite?
                  = image_tag "eventbritetag.png", :width=>"315", :heigh=>"115"

              = image_tag event.image_link, :class=>"img"
            %h5=event.event_name
            %p.event_text{style: "font-size:11px;"}
              =strip_tags(event.event_short_description)
              = link_to "Read more", event_path(event), class: 'btn-info'
            %p{style: "font-size:12px;"}
              %i.icon-calendar
              =event.date
            %p{style: "padding-left:1px;font-size:11px;"}
              %i.icon-map-marker{style:"font-size:12px"}
              - unless event.address.blank?
                =event.address
              - unless event.city.blank?
                =event.city
              - unless event.country.blank?
                =event.country
            %div#map-canvas

#wait_dialog.modal.fade.in{"aria-hidden" => "false", "style" => "display:none;"}
  .modal-header
    %h5{:style => "text-align:center !important"}
      We do our best to find you event, please wait.
      %br
  .modal-body
    %table
      %tbody
        %tr{:valign => "top"}
          %td{:style => "text-align:center !important"}
            %p
              %img{:alt => "Progress", :src => "/assets/progress.gif"}
            

:javascript
  var $ = $.noConflict(true);
  $("#start_date, #end_date").datepicker({
  "dateFormat":"dd-mm-yy"
  })

:javascript
  $("#search_button").click(function(){
     $("#wait_dialog").show();
     $("#new_search").submit();
  });

:javascript
  var page = 2;
  $(window).scroll(function () {
       if ($(window).scrollTop() == $(document).height() - $(window).height()) {
           getEvents();
           page = page+1;
       }
   });

:css
  .ui-datepicker-calendar {width:99% !important;}
  #ui-datepicker-div {width:14% !important;}

  function getEvents() {
       $.ajax(
        {
            type: "GET",
            url: "/",
            data: "page="+page,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            cache: "false",

            success: function (data) {
              $('#eventUl').append(data.html);
            },

            Error: function (x, e) {
                alert("Some error");
            }
        });
   }  

:css  
  .pac-container:after{background-image:none !important;} 

  -->

app/views/events/index.html.haml
= render :partial => "layouts/header"

.hero.hidden-phone
  .container
    .row
      .span12
        = image_tag "hero.png", :alt=>"1-1"
        -#%img{:alt => "1-1", :src => "img/hero.png"}/
        .calltoaction
          %h2.heading If it's out there we'll find it
          .description
            The way to discover and book interesting real events
.container
  .row-fluid
    %form.form-inline.search_bar
      Going
      %input.input-small{:placeholder => "From", :type => "text"}/
      %input.input-small{:placeholder => "To", :type => "text"}/
      In:
      %input{:placeholder => "Enter city name...", :type => "text"}/
      Interested in:
      %input{:placeholder => "lecture, meetups...", :type => "text"}/
      %button.btn{:type => "submit"} Search
      %span.pull-right
        %button.btn.btn-success{:type => "button"}
          %i.icon-map-marker
          Search by your place now
  .row-fluid.results
    .container-fluid
      %ul.thumbnails.span12.offset1
        - @data[:events].each do |event|
          %li.span3.pull-left{style: "box-shadow: 0 0 10px blanchedalmond, 0 0 2px blueviolet;height: 400px;margin-left: 0;margin-right: 50px;padding: 10px;"}
            %a.thumbnail{:href => "eventpage.html"}
              .tag
                - if event.from_meetup?
                  = image_tag "meetuptag.png"
                - if event.from_facebook?
                  = image_tag "facebooktag.png"
                - if event.from_eventbrite?
                  = image_tag "eventbritetag.png"

              = image_tag "1.jpeg"
            %h4=event.event_name
            %p.event_text
              =strip_tags(event.event_short_description)
              = link_to "Read more", event_path(event), class: 'btn-info'
            %p
              %i.icon-calendar
              =event.date
            %p{style: "padding-left:1px;"}
              %i.icon-map-marker{style:"font-size:16px"}
              location

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @event.name
%p
  %b Url:
  = @event.url
%p
  %b Source:
  = @event.source

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path