config/routes.rb
Eventsroundme::Application.routes.draw do
  get "normal_user/dashboard" =>"normal_user#dashboard"
  match "normal_user/add_event_normal_user" =>"normal_user#add_event_normal_user"
  match "normal_user/events_attending" =>"normal_user#events_attending"
  match "normal_user/find_friends" =>"normal_user#find_friends"
  match "normal_user/category_order" =>"normal_user#category_order"
  match "normal_user/create_event" =>"normal_user#create_event"
  match "normal_user/thank_you_after_payment" =>"normal_user#thank_you_after_payment"
  match "normal_user/paypal_notification" =>"normal_user#paypal_notification"
  match "normal_user/edit_event_by_normal_user/:id" =>"normal_user#edit_event_by_normal_user"
  match "normal_user/delete_user_event/:id" =>"normal_user#delete_user_event"
 
  root :to => "events#index"
  
  match "/contact"  => "contacts#new", as: :contact_us
  match "/test"   => "static#test"
  match '/auth/:provider/callback' => 'authentications#create'

  resources :contacts

  devise_for :admin_users, ActiveAdmin::Devise.config


  resources :searches

  get "events-in/(:name)/(:id)" => "searches#events_search", as: :events_search

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
 
  get "events/city/:name" => "searches#events_by_city"

  get "popup/events_around_me"
  get "popup/homepage"
  get "popup/signup"

  get "/fetch_event" => "events#fetch_event", :via => ["options", "get", "post"]
  get "/fetch_all_city" => "events#fetch_all_city", :via => ["options", "get", "post"]

  # get "/:action"    => "static#:action"

  resources :categories
  resources :events 
  ActiveAdmin.routes(self)  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :message, :subject
  validates_presence_of :email, :first_name, :message
end

app/controllers/contacts_controller.rb
class ContactsController < InheritedResources::Base
  actions :new, :create
  def create
    create!(notice: "", alert: "") do |success, failure|
      success.html { redirect_to contact_us_path, notice: "Feedback Submitted"}
      failure.html { render :new, alert: "Feedback Couldn't be submtted. Please try again later"}
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.haml
- unless alert.blank?
  %p.alert.span8=alert
- unless notice.blank? 
  %p.alert.span8=notice
= form_for @contact, html: {class: "well span8", style: "margin-left:0"} do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg
  .row{style: 'text-align:left;'}
    .span3
      .field
        = f.label :first_name
        = f.text_field :first_name, class: 'span3', placeholder: 'First name', required: true
      .field
        = f.label :last_name
        = f.text_field :last_name, class: 'span3', placeholder: 'Last name'
      .field
        = f.label :email
        = f.email_field :email, class: 'span3', placeholder: 'Email address', required: true
      .field
        = f.label :subject
        = f.select :subject, AppVar.contact_form_select_input_data
    .span5  
      .field
        = f.label :message
        = f.text_area :message, class: 'input-xlarge span5', placeholder: 'Enter your Message', rows: "12", required: true
    .span8
      .actions
        = f.submit 'Save', class: "btn-primary btn pull-right"

app/views/contacts/edit.html.haml
%h1 Editing contact

= render 'form'

= link_to 'Show', @contact
\|
= link_to 'Back', contacts_path

app/views/contacts/index.html.haml
%h1 Listing contacts

%table
  %tr
    %th First name
    %th Last name
    %th Email
    %th Subject
    %th Message
    %th
    %th
    %th

  - @contacts.each do |contact|
    %tr
      %td= contact.first_name
      %td= contact.last_name
      %td= contact.email
      %td= contact.subject
      %td= contact.message
      %td= link_to 'Show', contact
      %td= link_to 'Edit', edit_contact_path(contact)
      %td= link_to 'Destroy', contact, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Contact', new_contact_path

app/views/contacts/new.html.haml
.container.span12{style: "text-align:center;"}
  %h1{style:"text-align:left;"} Contact us
  = render 'form'

app/views/contacts/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @contact.first_name
%p
  %b Last name:
  = @contact.last_name
%p
  %b Email:
  = @contact.email
%p
  %b Subject:
  = @contact.subject
%p
  %b Message:
  = @contact.message

= link_to 'Edit', edit_contact_path(@contact)
\|
= link_to 'Back', contacts_path