config/routes.rb
Eventsroundme::Application.routes.draw do
  get "normal_user/dashboard" =>"normal_user#dashboard"
  match "normal_user/add_event_normal_user" =>"normal_user#add_event_normal_user"
  match "normal_user/events_attending" =>"normal_user#events_attending"
  match "normal_user/find_friends" =>"normal_user#find_friends"
  match "normal_user/category_order" =>"normal_user#category_order"
  match "normal_user/create_event" =>"normal_user#create_event"
  match "normal_user/thank_you_after_payment" =>"normal_user#thank_you_after_payment"
  match "normal_user/paypal_notification" =>"normal_user#paypal_notification"
  match "normal_user/edit_event_by_normal_user/:id" =>"normal_user#edit_event_by_normal_user"
  match "normal_user/delete_user_event/:id" =>"normal_user#delete_user_event"
 
  root :to => "events#index"
  
  match "/contact"  => "contacts#new", as: :contact_us
  match "/test"   => "static#test"
  match '/auth/:provider/callback' => 'authentications#create'

  resources :contacts

  devise_for :admin_users, ActiveAdmin::Devise.config


  resources :searches

  get "events-in/(:name)/(:id)" => "searches#events_search", as: :events_search

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
 
  get "events/city/:name" => "searches#events_by_city"

  get "popup/events_around_me"
  get "popup/homepage"
  get "popup/signup"

  get "/fetch_event" => "events#fetch_event", :via => ["options", "get", "post"]
  get "/fetch_all_city" => "events#fetch_all_city", :via => ["options", "get", "post"]

  # get "/:action"    => "static#:action"

  resources :categories
  resources :events 
  ActiveAdmin.routes(self)  
end

app/models/search.rb
class Search < ActiveRecord::Base
  attr_accessible :ip_address, :search_string
  serialize :search_string
  serialize :event_list
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_filter :set_data_variable

  def set_data_variable
    @data = Hash.new
  end

  def events_search
    # {"name"=>"Devere-hotel", "id"=>"170"}
    # {"name"=>"Delhi-india", "id"=>"64"}

    @search_name = params[:name]
    @search_id = params[:id]
    @search = Search.find(params[:id])
    if @search.event_list.blank?
      event_list = Event.new.combined_search_results(@search.search_string)
      @search.update_attribute :event_list, event_list
    end
    event_list = event_list.blank? ? @search.event_list : event_list

    if event_list.blank?
      @data[:events] = []
    elsif event_list.count == 1
      @data[:events] = Event.where("id in (#{event_list.join})")
    elsif event_list.count > 1
      @data[:events] = Event.where("id in (#{event_list.join(',')}) AND starting_at > '#{Time.now.to_date}'")
    end

    unless @data[:events].nil?
      @events_array = []
      @data[:events].each do |event|
        @match_city = 0
        
        final_address_string = (event.address + event.city + event.country + event.state).split(/\s+(?=(?:[^"]*"[^"]*")*[^"]*$)/);
        search_string = @search.search_string[:city].gsub(/\s+/, ' ').split(" ");

        search_string.each do |f|
          final_address_string.each do |ff|
            unless ff.downcase.match(f.downcase).nil?
              @match_city = @match_city+1
            end
          end          
        end

        unless @search.search_string[:start_date].blank?
          if event.starting_at.to_date >= @search.search_string[:start_date].to_date and @match_city == search_string.count
            @events_array << event
          end
        else
          if @match_city == search_string.count
            @events_array << event
          end
        end  
        
      end
      @data[:events] = @events_array
      @data[:events] = @data[:events].sort { |x,y| y.starting_at.to_date <=> x.starting_at.to_date }
      @data[:events] = @data[:events].reverse
    end  

    unless @data[:events].nil?
      if params[:page].nil?
        @data[:events] = @data[:events].first(9);
      else
        limit = params[:page].to_i*9
        @data[:events] = @data[:events].drop(limit-9).first(9);
      end      
    end

    respond_to do |format|
      format.html { render :show }
      #format.json { render json: @search }
      format.json { render :json => {:html => render_to_string(:partial => "event.html.haml")}.to_json }
    end
  end

  # GET /searches
  # GET /searches.json
  def index
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])
    unless @search.event_list.blank?
      event_list = Event.new.combined_search_results(@search.search_string)
    end

    @search.update_attribute :event_list, event_list

    @data[:events] = Event.find(event_list).sort_by(&:starting_at)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.json
  def create
    # "start_date"=>"30-11-2013", "end_date"=>"24-01-2014",

    params[:location] = params[:location].downcase.gsub("-"," ").gsub(","," ").gsub(/\s+/, ' ');

    # location_text = params[:location]
    # unless location_text.split(",").blank?
    #   unless location_text.split(",")[0].blank?
    #     params[:location] = location_text.split(",")[0]
    #   end
    # end
    
    @search_string = {
      start_date: (Date.parse(params[:start_date]) rescue ''),
      end_date: (Date.parse(params[:end_date]) rescue ''),
      city: (params[:location] rescue ''),
      text: (params[:search_string] rescue ''),
      site: (params[:select_site] rescue '')
    }

    @search = Search.where(search_string: @search_string.to_yaml)
    
    if @search.blank? || (@search.first.created_at < (Date.today - 1.week)) 
      @search = Search.new(
        :search_string => @search_string,
        :ip_address => params[:search][:ip_address]
      )
      respond_to do |format|
        if @search.save
          format.html { redirect_to events_search_path(Event.new.seo_city_name(@search.search_string[:city]),@search.id)} 
        else
          format.html { redirect_to :back, alert: "Some error has occured"}
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to events_search_path(Event.new.seo_city_name(@search.first.search_string[:city]),@search.first.id)}
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.json
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end

  def events_by_city
    city = params[:name]
    options = {city: city,text: "event"}
    @events = Event.new.combined_search_results(options)
    respond_to do |format|
      format.html
      format.json
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_event.html.erb
<% @data[:events].each do |event| %>
                      <div class="event">
                          <div class="event_head">
                            <% if event.from_meetup? %>
                                  <a href="<%= event.image_link%>"><img src="/assets/meet.png"/></a>
                              <% elsif event.from_facebook? %>
                                  <a href="<%= event.image_link%>"><img src="/assets/f.png"/></a>
                              <% elsif event.from_eventbrite?%>
                                  <a href="<%= event.image_link%>"><img src="/assets/e.png"/></a>
                              <% end %>                              
                              <p><img src="/assets/location_icon.png"/>
                                <% if event.city.blank? and event.country.blank? %>
                                  <%= event.address %>
                                <% else %>
                                  <%= event.city %>, <%= event.country%>
                                <% end %>                                
                              </p>
                              <p><img src="/assets/calender_icon.png"/><%= event.date%></p>
                          </div>
                          <div class="event_body">
                              <a href="<%=event_path(event)%>" class="search_img"><img src="<%= event.image_link%>"/></a>
                              <a href="<%=event_path(event)%>"><h3 style="font-size:25px !important; color:inherit !important;"><%= event.event_name%></h3></a>
                              <p style="font-size:16px !important;"><%=strip_tags(event.event_short_description)%></p>
                          </div>
                      </div>
                    <% end %>


<!-- - @data[:events].each do |event|
  %li.span3.pull-left{style: "box-shadow: 0 0 10px blanchedalmond, 0 0 2px blueviolet;height: 400px;margin-left: 0;margin-right: 50px;padding: 10px;"}
    %a.thumbnail{:href => event_path(event)}
      .tag
        - if event.from_meetup?
          = image_tag "meetuptag.png"
        - if event.from_facebook?
          = image_tag "facebooktag.png"
        - if event.from_eventbrite?
          = image_tag "eventbritetag.png", :width=>"315", :heigh=>"115"

      = image_tag event.image_link, :class=>"img"
    %h5=event.event_name
    %p.event_text{style: "font-size:11px;"}
      =strip_tags(event.event_short_description)
      = link_to "Read more", event_path(event), class: 'btn-info'
    %p{style: "font-size:12px;"}
      %i.icon-calendar
      =event.date
    %p{style: "padding-left:1px;font-size:11px;"}
      %i.icon-map-marker{style:"font-size:12px"}
      - unless event.address.blank?
        =event.address
      - unless event.city.blank?
        =event.city
      - unless event.country.blank?
        =event.country -->

app/views/searches/_form.html.haml
= form_for @search do |f|
  - if @search.errors.any?
    #error_explanation
      %h2= "#{pluralize(@search.errors.count, "error")} prohibited this search from being saved:"
      %ul
        - @search.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :search_string
    = f.text_area :search_string
  .field
    = f.label :ip_address
    = f.text_field :ip_address
  .actions
    = f.submit 'Save'

app/views/searches/edit.html.haml
%h1 Editing search

= render 'form'

= link_to 'Show', @search
\|
= link_to 'Back', searches_path

app/views/searches/events_by_city.html.haml
=@events

app/views/searches/index.html.haml
%h1 Listing searches

%table
  %tr
    %th Search string
    %th Ip address
    %th
    %th
    %th

  - @searches.each do |search|
    %tr
      %td= search.search_string
      %td= search.ip_address
      %td= link_to 'Show', search
      %td= link_to 'Edit', edit_search_path(search)
      %td= link_to 'Destroy', search, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Search', new_search_path

app/views/searches/new.html.haml
%h1 New search

= render 'form'

= link_to 'Back', searches_path

app/views/searches/show.html.erb
<%= content_for :head do %>
  <title>"Events in <%= params[:name] %> | Find events around me"</title>
<% end %> 

    <div class="container">
        <div class="row-fluid">
            <div class="span11">
                <div class="" id="eventUl">
                  <% unless @data[:events].blank? %>
                    <% @data[:events].each do |event| %>
                    <%= hidden_field_tag "city_name", @search_name %>
                    <%= hidden_field_tag "search_id", @search_id %>
                      <div class="event">
                          <div class="event_head">
                            <% if event.from_meetup? %>
                                  <a href="<%= event.image_link%>"><img src="/assets/meet.png"/></a>
                              <% elsif event.from_facebook? %>
                                  <a href="<%= event.image_link%>"><img src="/assets/f.png"/></a>
                              <% elsif event.from_eventbrite?%>
                                  <a href="<%= event.image_link%>"><img src="/assets/e.png"/></a>
                              <% end %>                              
                              <p><img src="/assets/location_icon.png"/>
                                <% if event.city.blank? and event.country.blank? %>
                                  <%= event.address %>
                                <% else %>
                                  <%= event.city %>, <%= event.country%>
                                <% end %>                                
                              </p>
                              <p><img src="/assets/calender_icon.png"/><%= event.date%></p>
                          </div>
                          <div class="event_body">
                              <a href="<%=event_path(event)%>" class="search_img"><img src="<%= event.image_link%>"/></a>
                              <a href="<%=event_path(event)%>"><h3 style="font-size:22px !important; color:inherit !important;"><%= event.event_name%></h3></a>
                              <p style="font-size:16px !important;"><%=strip_tags(event.event_short_description)%></p>
                          </div>
                      </div>
                    <% end %>
                  <% else %>  
                    <div class="event">
                          <div class="event_head">
                            <h2 style="text-align:center;">No Event Found.</h2>
                          </div>
                    </div>      
                  <% end %>  
                </div>
            </div>            
        </div>
    </div>


<script type="text/javascript">
  var page = 2;
  $(window).scroll(function () {
       if ($(window).scrollTop() == $(document).height() - $(window).height()) {
           getEvents();
           page = page+1;
       }
   });

  function getEvents() {
      var search_name = $("#search_name").val();
      var search_id = $("#search_id").val();
       $.ajax(
        {
            type: "GET",
            url: "/events-in/"+search_name+"/"+search_id,
            data: "page="+page,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            cache: "false",

            success: function (data) {
              $('#eventUl').append(data.html);
            },

            Error: function (x, e) {
                alert("Some error");
            }
        });
   }
</script>

<!-- :css
  .offset1 {margin-top:7%;}
=content_for :head do
  %title="Events in #{params[:name]} | Find events around me"

- unless @data[:events].blank?
  .row-fluid.results
    .container-fluid
      %ul.thumbnails.span12.offset1#eventUl
        = hidden_field_tag "city_name", @search_name
        = hidden_field_tag "search_id", @search_id
        - @data[:events].each do |event|
          %li.span3.pull-left{style: "box-shadow: 0 0 10px blanchedalmond, 0 0 2px blueviolet;height: 400px;margin-left: 0;margin-right: 50px;padding: 10px;"}
            %a.thumbnail{:href => event_path(event)}
              .tag
                - if event.from_meetup
                  = image_tag "meetuptag.png"
                - if event.from_facebook
                  = image_tag "facebooktag.png"
                - if event.from_eventbrite
                  = image_tag "eventbritetag.png"
              = image_tag event.image_link, :class=>"img"
            %h5=event.event_name
            %p.event_text{style: "font-size:11px;"}
              = strip_tags(event.event_short_description)
              = link_to "Read more", event_path(event), class: 'btn-info'
            %p{style: "font-size:12px;"}
              %i.icon-calendar
              =event.date
            %p{style: "padding-left:1px;font-size:11px;"}
              %i.icon-map-marker{style:"font-size:12px"}
              - unless event.address.blank?
                =event.address
              - unless event.city.blank?
                =event.city
              - unless event.country.blank?
                =event.country
- else
  %h3 No events found

     -->

app/views/searches/show.html.haml
:css
  .offset1 {margin-top:7%;}
=content_for :head do
  %title="Events in #{params[:name]} | Find events around me"

- unless @data[:events].blank?
  .row-fluid.results
    .container-fluid
      %ul.thumbnails.span12.offset1#eventUl
        = hidden_field_tag "city_name", @search_name
        = hidden_field_tag "search_id", @search_id
        - @data[:events].each do |event|
          %li.span3.pull-left{style: "box-shadow: 0 0 10px blanchedalmond, 0 0 2px blueviolet;height: 400px;margin-left: 0;margin-right: 50px;padding: 10px;"}
            %a.thumbnail{:href => event_path(event)}
              .tag
                - if event.from_meetup
                  = image_tag "meetuptag.png"
                - if event.from_facebook
                  = image_tag "facebooktag.png"
                - if event.from_eventbrite
                  = image_tag "eventbritetag.png"
              = image_tag event.image_link, :class=>"img"
            %h5=event.event_name
            %p.event_text{style: "font-size:11px;"}
              = strip_tags(event.event_short_description)
              = link_to "Read more", event_path(event), class: 'btn-info'
            %p{style: "font-size:12px;"}
              %i.icon-calendar
              =event.date
            %p{style: "padding-left:1px;font-size:11px;"}
              %i.icon-map-marker{style:"font-size:12px"}
              - unless event.address.blank?
                =event.address
              - unless event.city.blank?
                =event.city
              - unless event.country.blank?
                =event.country
- else
  %h3 No events found


:javascript
  var page = 2;
  $(window).scroll(function () {
       if ($(window).scrollTop() == $(document).height() - $(window).height()) {
           getEvents();
           page = page+1;
       }
   });

  function getEvents() {
      var search_name = $("#search_name").val();
      var search_id = $("#search_id").val();
       $.ajax(
        {
            type: "GET",
            url: "/events-in/"+search_name+"/"+search_id,
            data: "page="+page,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            cache: "false",

            success: function (data) {
              $('#eventUl').append(data.html);
            },

            Error: function (x, e) {
                alert("Some error");
            }
        });
   }    