config/routes.rb
Eventsroundme::Application.routes.draw do
  get "normal_user/dashboard" =>"normal_user#dashboard"
  match "normal_user/add_event_normal_user" =>"normal_user#add_event_normal_user"
  match "normal_user/events_attending" =>"normal_user#events_attending"
  match "normal_user/find_friends" =>"normal_user#find_friends"
  match "normal_user/category_order" =>"normal_user#category_order"
  match "normal_user/create_event" =>"normal_user#create_event"
  match "normal_user/thank_you_after_payment" =>"normal_user#thank_you_after_payment"
  match "normal_user/paypal_notification" =>"normal_user#paypal_notification"
  match "normal_user/edit_event_by_normal_user/:id" =>"normal_user#edit_event_by_normal_user"
  match "normal_user/delete_user_event/:id" =>"normal_user#delete_user_event"
 
  root :to => "events#index"
  
  match "/contact"  => "contacts#new", as: :contact_us
  match "/test"   => "static#test"
  match '/auth/:provider/callback' => 'authentications#create'

  resources :contacts

  devise_for :admin_users, ActiveAdmin::Devise.config


  resources :searches

  get "events-in/(:name)/(:id)" => "searches#events_search", as: :events_search

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
 
  get "events/city/:name" => "searches#events_by_city"

  get "popup/events_around_me"
  get "popup/homepage"
  get "popup/signup"

  get "/fetch_event" => "events#fetch_event", :via => ["options", "get", "post"]
  get "/fetch_all_city" => "events#fetch_all_city", :via => ["options", "get", "post"]

  # get "/:action"    => "static#:action"

  resources :categories
  resources :events 
  ActiveAdmin.routes(self)  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :shortname, :meetup_category_id
  def category_short_name
    "#{self.shortname}"
end	
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :shortname
    = f.text_field :shortname
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %tr
    %th Name
    %th Shortname
    %th
    %th
    %th

  - @categories.each do |category|
    %tr
      %td= category.name
      %td= category.shortname
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b Shortname:
  = @category.shortname

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path